[book]
title = "camdl"
description = "Compartmental Model Description Language"
authors = ["Vince Buffalo"]
language = "en"
src = "src"

[build]
build-dir = "../../target/book"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/idm-tools/camdl"
edit-url-template = "https://github.com/idm-tools/camdl/edit/main/docs/book/src/{path}"
additional-js = ["mathjax.js"]
