//! External-harness driver binary.
//!
//! See docs/dev/proposals/2026-04-23-external-validation-harness.md.

mod compare;
mod hashing;
mod manifest;
mod runner;
mod subprocess;
mod summarise;
mod summary;

use clap::{Parser, Subcommand};
use runner::Status;
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "external-harness", version,
          about = "Run camdl against cached external reference outputs")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Run a specific case's fast path (cached fixture only; no regen).
    Run {
        /// Path to the case directory (contains case.toml).
        case: PathBuf,
    },
    /// List all cases in `tests/external/cases/`.
    #[allow(dead_code)]
    List {
        #[arg(long, default_value = "tests/external/cases")]
        root: PathBuf,
    },
    /// Compute current reference_sha + case_sha for a case and print them
    /// (or write a fresh MANIFEST stub with --write). Used to bootstrap a
    /// fixture MANIFEST after authoring case.toml / expected.toml /
    /// reference/ content — the summary.tsv content is up to the case
    /// author (hand-written for analytical cases, generated by regen
    /// for external-tool cases).
    Bootstrap {
        case: PathBuf,
        /// Write fixtures/MANIFEST.toml (requires fixtures/summary.tsv to
        /// exist so fixture_sha can be computed).
        #[arg(long)]
        write: bool,
        /// Seed base and n_seeds to record in the MANIFEST. Read from
        /// case.toml if not supplied.
        #[arg(long)]
        seed_base: Option<u64>,
        #[arg(long)]
        n_seeds: Option<usize>,
    },
}

fn main() {
    let cli = Cli::parse();
    match cli.command {
        Command::Run { case } => {
            let outcome = runner::run_case(&case).unwrap_or_else(|e| {
                eprintln!("harness error: {:#}", e);
                std::process::exit(2);
            });
            report(&outcome);
            match outcome.status {
                Status::Pass              => std::process::exit(0),
                Status::Stale(_)
                | Status::Crash(_)
                | Status::ToleranceFail   => std::process::exit(1),
            }
        }
        Command::Bootstrap { case, write, seed_base, n_seeds } => {
            if let Err(e) = bootstrap(&case, write, seed_base, n_seeds) {
                eprintln!("bootstrap error: {:#}", e);
                std::process::exit(2);
            }
        }
        Command::List { root } => {
            let cases = std::fs::read_dir(&root).unwrap_or_else(|e| {
                eprintln!("cannot read {}: {}", root.display(), e);
                std::process::exit(2);
            });
            for entry in cases.flatten() {
                if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                    println!("{}", entry.path().display());
                }
            }
        }
    }
}

fn bootstrap(
    case_dir: &std::path::Path,
    write: bool,
    seed_base_override: Option<u64>,
    n_seeds_override: Option<usize>,
) -> anyhow::Result<()> {
    use manifest::{CaseManifest, FixtureManifest};
    let case_text = std::fs::read_to_string(case_dir.join("case.toml"))
        .map_err(|e| anyhow::anyhow!("read case.toml: {}", e))?;
    let case: CaseManifest = toml::from_str(&case_text)
        .map_err(|e| anyhow::anyhow!("parse case.toml: {}", e))?;

    let reference_sha = runner::compute_reference_sha(&case.reference, case_dir)?;
    let case_sha = runner::compute_case_sha(&case, case_dir)?;
    let seed_base = seed_base_override.unwrap_or(case.camdl.seed_base);
    let n_seeds = n_seeds_override.unwrap_or(case.camdl.n_seeds);

    println!("reference_sha = {}", reference_sha);
    println!("case_sha      = {}", case_sha);
    println!("harness_version = {}", runner::HARNESS_VERSION);
    println!("seed_base = {}", seed_base);
    println!("n_seeds = {}", n_seeds);

    if !write { return Ok(()); }

    let summary_path = case_dir.join("fixtures").join("summary.tsv");
    if !summary_path.exists() {
        return Err(anyhow::anyhow!(
            "fixtures/summary.tsv must exist before --write (author it first, \
             then re-run bootstrap)"));
    }
    let fixture_sha = hashing::sha256_file(&summary_path)?;

    let manifest = FixtureManifest {
        reference_sha, case_sha,
        harness_version: runner::HARNESS_VERSION.to_string(),
        fixture_sha,
        pomp_version: None, r_version: None, python_version: None,
        generated_at: chrono::Utc::now().to_rfc3339(),
        generated_on: Some(format!("{}-{}", std::env::consts::OS, std::env::consts::ARCH)),
        generated_command: Some("external-harness bootstrap".to_string()),
        generated_in_docker: false,
        n_seeds_reference: n_seeds,
        seed_base,
    };
    let manifest_path = case_dir.join("fixtures").join("MANIFEST.toml");
    let text = toml::to_string_pretty(&manifest)
        .map_err(|e| anyhow::anyhow!("serialize MANIFEST: {}", e))?;
    std::fs::write(&manifest_path, text)
        .map_err(|e| anyhow::anyhow!("write {}: {}", manifest_path.display(), e))?;
    println!("wrote {}", manifest_path.display());
    Ok(())
}

fn report(outcome: &runner::CaseOutcome) {
    match &outcome.status {
        Status::Pass => {
            println!("PASS {} ({} checks)", outcome.name, outcome.checks.len());
            for c in &outcome.checks {
                println!("  ok  {} [{}]", c.stat, c.kind_description);
            }
        }
        Status::Stale(msg) => {
            eprintln!("STALE {}", outcome.name);
            eprintln!("{}", msg);
        }
        Status::Crash(msg) => {
            eprintln!("CRASH {}", outcome.name);
            eprintln!("{}", msg);
        }
        Status::ToleranceFail => {
            eprintln!("FAIL {}", outcome.name);
            for c in &outcome.checks {
                let marker = match c.outcome {
                    compare::Outcome::Pass => "ok  ",
                    compare::Outcome::Fail => "FAIL",
                };
                eprintln!("  {} {} [{}] — {}",
                    marker, c.stat, c.kind_description, c.detail);
            }
            eprintln!("run directory: {}", outcome.run_dir.display());
        }
    }
}
