//! `fit_state.toml` — inter-stage handoff file.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Serialize, Deserialize)]
pub struct FitState {
    pub stage: String,
    pub seed: u64,
    pub timestamp: String,
    /// Input hash identifying the computation that produced this state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_hash: Option<String>,
    /// camdl version that produced this state (e.g. "0.1.0+ce78a5e").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub camdl_version: Option<String>,
    pub best_loglik: f64,
    pub initial_loglik: f64,
    pub best_chain: usize,
    pub n_chains: usize,
    pub n_good_chains: Option<usize>,
    pub start_values: HashMap<String, f64>,
    pub rw_sd: HashMap<String, f64>,
    /// What kind of log-likelihood is in `best_loglik`.
    /// "marginal" (PMMH), "complete_data" (PGAS), "if2" (IF2/scout/refine).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub loglik_type: Option<String>,
    /// Overall acceptance rate of the best chain (PGAS/PMMH only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acceptance_rate: Option<f64>,

    /// Per-parameter tail-Rhat (last half of iterations). Populated at
    /// end-of-stage so downstream stages (notably refine) can gate on
    /// scout's convergence without re-running. Absent in legacy
    /// fit_state.toml files — downstream readers must treat absence as
    /// "unknown, proceed with warning," not "converged."
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub tail_rhat: HashMap<String, f64>,

    /// Names of estimated parameters declared `ivp = true`. Refine's
    /// Rhat gate exempts these — IVP parameters are expected to be
    /// harder to identify and shouldn't block the pipeline when
    /// structural convergence is fine. Stored here (not re-derived
    /// from fit.toml in the downstream) so the two can't drift.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub ivp_params: Vec<String>,

    /// Per-chain final log-likelihoods (the full distribution behind
    /// `best_loglik`). Refine's post-run loglik-regression gate uses
    /// the spread to compute its tolerance ε. Short vector; cheap to
    /// serialise.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub chain_logliks: Vec<f64>,
}

impl FitState {
    pub fn load(dir: &str) -> Result<Self, String> {
        let path = format!("{}/fit_state.toml", dir);
        let contents = std::fs::read_to_string(&path)
            .map_err(|e| format!("cannot read {}: {}", path, e))?;
        toml::from_str(&contents)
            .map_err(|e| format!("parse error in {}: {}", path, e))
    }

    pub fn save(&self, dir: &str) -> Result<(), String> {
        let path = format!("{}/fit_state.toml", dir);
        let body = toml::to_string_pretty(self)
            .map_err(|e| format!("serialize error: {}", e))?;
        let contents = format!("# Generated by {}\n{}", crate::version::VERSION, body);
        std::fs::write(&path, contents)
            .map_err(|e| format!("cannot write {}: {}", path, e))
    }
}
