//! Cross-validate camdl's periodic B-spline evaluator against two
//! independent external oracles: scipy.interpolate.BSpline (Python)
//! and pomp::periodic_bspline_basis (R).
//!
//! The TSV fixtures live in `tests/fixtures/` and are regenerated by
//! `scripts/gen_periodic_bspline_*.{py,R}`. CI loads the committed
//! TSVs and never depends on Python/R being installed.
//!
//! If either oracle and camdl agree, that's evidence the algorithm
//! is right. If both agree, we have independent verification from
//! two ecosystems with non-overlapping code paths — the strongest
//! correctness signal available for numerical code at this layer.

use sim::periodic_bspline::eval_periodic_bspline;
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

/// Read a `(t, y)` TSV with `#`-prefixed comment lines. Returns the
/// parsed pairs in file order. Panics on malformed input.
fn read_tsv_pairs(path: &Path) -> Vec<(f64, f64)> {
    let f = File::open(path).unwrap_or_else(|e|
        panic!("could not open {}: {}", path.display(), e));
    let mut out = Vec::new();
    for line in BufReader::new(f).lines() {
        let line = line.unwrap();
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("t\t") {
            continue;
        }
        let cols: Vec<&str> = trimmed.split('\t').collect();
        assert_eq!(cols.len(), 2, "expected 2 columns, got {:?}", cols);
        let t: f64 = cols[0].parse().unwrap();
        let y: f64 = cols[1].parse().unwrap();
        out.push((t, y));
    }
    out
}

/// Fixed test parameters; must match the fixture generators.
fn fixture_params() -> (f64, u32, u32, Vec<f64>) {
    (
        4.0,                                    // period
        6,                                      // n_basis
        3,                                      // degree
        vec![0.7, 1.2, 0.9, 0.5, 1.1, 0.8],     // coefs
    )
}

#[test]
fn periodic_bspline_matches_scipy() {
    let path = Path::new("tests/fixtures/periodic_bspline_scipy.tsv");
    let pairs = read_tsv_pairs(path);
    assert!(!pairs.is_empty(), "scipy fixture is empty");

    let (period, n_basis, degree, coefs) = fixture_params();
    let mut max_diff: f64 = 0.0;
    for (t, expected) in &pairs {
        let actual = eval_periodic_bspline(*t, period, n_basis, degree, &coefs);
        let diff = (actual - expected).abs();
        if diff > max_diff { max_diff = diff; }
    }
    assert!(
        max_diff < 1e-12,
        "camdl vs scipy max |diff| = {:.3e}; threshold 1e-12", max_diff
    );
}

#[test]
fn periodic_bspline_matches_pomp() {
    let path = Path::new("tests/fixtures/periodic_bspline_pomp.tsv");
    let pairs = read_tsv_pairs(path);
    assert!(!pairs.is_empty(), "pomp fixture is empty");

    let (period, n_basis, degree, coefs) = fixture_params();
    let mut max_diff: f64 = 0.0;
    for (t, expected) in &pairs {
        let actual = eval_periodic_bspline(*t, period, n_basis, degree, &coefs);
        let diff = (actual - expected).abs();
        if diff > max_diff { max_diff = diff; }
    }
    assert!(
        max_diff < 1e-12,
        "camdl vs pomp max |diff| = {:.3e}; threshold 1e-12", max_diff
    );
}
